apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-auto-deploy
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/applications
    repoURL:  {{ applications_destination_repo }}
    targetRevision: HEAD
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
