{{- if .Values.cm.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.appId }}"
  labels:
    app: "{{ .Values.appId }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
{{- tpl (include "env_vars_global" .) . | indent 2 -}}
  {{- range $key, $val := .Values.cm.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- tpl (include "env_vars" .) . | indent 2 -}}
{{- end }}
