{{- if .Values.deployment.horizontalScaler.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.appId }}
  labels:
    app: {{ .Values.appId }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  maxReplicas: {{ .Values.deployment.horizontalScaler.maxReplicas }}
  minReplicas: {{ .Values.deployment.horizontalScaler.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.deployment.horizontalScaler.kind }}
    name: {{ .Values.appId }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.deployment.horizontalScaler.targetCpuUtil }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.deployment.horizontalScaler.targetMemUtil }}
{{- end }}
