{{- if not .Values.secretEnv.enabled -}}
{{- if .Values.externalsecretEnv.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.appId }}-env-secret
  labels:
    app: {{ .Values.appId }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore-aws
    kind: ClusterSecretStore
  target:
    name: {{ .Values.appId }}-external-secret
    creationPolicy: Owner
  data:
    {{- range .Values.externalsecretEnv.env }}
    - secretKey: {{ .name }}
      remoteRef:
        key: {{ .key }}
        property: {{ .property }}
    {{- end -}}
{{- end }}
{{- end }}
