{{- if .Values.secretEnv.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appId }}-env
  labels:
    app: {{ .Values.appId }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- range $key, $val := .Values.secretEnv.env }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
