{{- if .Values.secretFile.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appId }}-file
  labels:
    app: {{ .Values.appId }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- range $i, $file := .Values.secretFile.files }}
  {{ $file.fileName }}: {{ $file.content | b64enc | quote }}
  {{- end }}
{{- end }}
