{{- if .Values.service.external -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appId }}-{{ .Release.Namespace }}
  namespace: ingress-nginx
  labels:
    app: {{ .Values.appId }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ExternalName
  externalName: {{ .Values.appId }}.{{ .Release.Namespace }}
  ports:
  - name: api
    port: 80
    protocol: TCP
    targetPort: 80
{{- end }}
